"""PDF Generation Service — creates downloadable PDFs for billing forms and reports."""
import io
import logging
from datetime import datetime

logger = logging.getLogger(__name__)


try:
    import fitz  # PyMuPDF
    HAS_FITZ = True
except ImportError:
    HAS_FITZ = False
    logger.error("PyMuPDF not installed — PDF generation disabled")


# ─── PDF Drawing Helpers ──────────────────────────────────────────────────────

def _draw_header(page, title: str, subtitle: str = None):
    """Draw page header with title and branding."""
    page.draw_rect(fitz.Rect(0, 0, 595, 80), color=None, fill=(0.22, 0.27, 0.55))
    page.insert_text((30, 35), title, fontsize=18, color=(1, 1, 1), fontname="helv")
    sub = subtitle or f"SAMHITA — Billing Intelligence | {datetime.now().strftime('%d %b %Y')}"
    page.insert_text((30, 58), sub, fontsize=8, color=(0.8, 0.8, 0.9), fontname="helv")


def _draw_footer(page, text: str, page_num: int = 1):
    """Draw page footer."""
    page.insert_text((30, 820), text, fontsize=7, color=(0.5, 0.5, 0.5), fontname="helv")
    page.insert_text((520, 820), f"Page {page_num}", fontsize=7, color=(0.5, 0.5, 0.5), fontname="helv")


def _draw_section_header(page, title: str, y: float) -> float:
    """Draw a section header and return new y position."""
    page.draw_rect(fitz.Rect(30, y, 565, y + 20), color=None, fill=(0.93, 0.93, 0.97))
    page.insert_text((35, y + 14), title, fontsize=9, color=(0.22, 0.27, 0.55), fontname="helv")
    return y + 28


def _draw_fields(page, fields: list[tuple], y: float, label_x=35, value_x=180) -> float:
    """Draw label-value pairs."""
    for label, value in fields:
        val = str(value) if value else "—"
        page.insert_text((label_x, y + 12), f"{label}:", fontsize=8, color=(0.4, 0.4, 0.4), fontname="helv")
        page.insert_text((value_x, y + 12), val, fontsize=9, color=(0.1, 0.1, 0.1), fontname="helv")
        y += 18
    return y


def _draw_text(page, text: str, y: float, size: int = 9, color=(0.1, 0.1, 0.1), bold=False, x=35, max_width=530) -> float:
    """Draw a line of text with word wrapping."""
    # Simple word wrap
    words = text.split()
    lines = []
    current = ""
    for word in words:
        test = f"{current} {word}".strip()
        # rough char width estimate
        if len(test) * (size * 0.5) > max_width:
            if current:
                lines.append(current)
            current = word
        else:
            current = test
    if current:
        lines.append(current)

    for line in lines:
        page.insert_text((x, y + size + 2), line, fontsize=size, color=color, fontname="helv")
        y += size + 4
    return y


def _draw_table_row(page, cols: list[tuple], y: float, size=8, color=(0.1, 0.1, 0.1), header=False) -> float:
    """Draw a table row. cols = [(text, x_pos), ...]"""
    if header:
        page.draw_rect(fitz.Rect(30, y, 565, y + 16), color=None, fill=(0.93, 0.93, 0.97))
    for text, x in cols:
        page.insert_text((x, y + 11), str(text), fontsize=size, color=color, fontname="helv")
    return y + 17


# ─── Document Summary PDF ────────────────────────────────────────────────────

def generate_document_pdf(doc_data: dict, entities: list[dict], extracted_data: dict = None) -> bytes:
    """Generate a clean clinical summary PDF from extracted document data."""
    if not HAS_FITZ:
        return b""

    doc = fitz.open()
    page = doc.new_page(width=595, height=842)
    page_num = 1

    def check_page(pg, y_pos, needed=40):
        nonlocal page_num
        if y_pos > 800 - needed:
            _draw_footer(pg, "Generated by Samhita Billing Intelligence", page_num)
            pg = doc.new_page(width=595, height=842)
            page_num += 1
            return pg, 50
        return pg, y_pos

    ext = extracted_data or {}
    patient_name = ext.get("patient_name") or "Unknown"

    _draw_header(page, "CLINICAL SUMMARY REPORT", f"Patient: {patient_name} | {datetime.now().strftime('%d %b %Y %H:%M')}")

    y = 95

    # ── Patient Demographics ──
    y = _draw_section_header(page, "PATIENT INFORMATION", y)
    fields = [
        ("Patient Name", patient_name),
        ("Age", ext.get("patient_age", "")),
        ("Gender", ext.get("patient_gender", "")),
        ("Patient ID", ext.get("patient_id", "")),
        ("Admission Date", ext.get("admission_date", "")),
        ("Discharge Date", ext.get("discharge_date", "")),
    ]
    # Filter out empty fields
    fields = [(k, v) for k, v in fields if v]
    y = _draw_fields(page, fields, y)

    # ── Document Info ──
    page, y = check_page(page, y + 5)
    y = _draw_section_header(page, "DOCUMENT DETAILS", y)
    confidence = doc_data.get("confidence_score", 0) or 0
    fields = [
        ("File Name", doc_data.get("filename", "")),
        ("Pages", doc_data.get("page_count", 1)),
        ("AI Confidence", f"{confidence * 100:.0f}%"),
        ("Status", (doc_data.get("status") or "").replace("_", " ").title()),
    ]
    y = _draw_fields(page, fields, y)

    # ── Diagnoses ──
    diagnoses = ext.get("diagnoses", [])
    if diagnoses:
        page, y = check_page(page, y + 5)
        y = _draw_section_header(page, f"DIAGNOSES ({len(diagnoses)})", y)
        for i, dx in enumerate(diagnoses, 1):
            page, y = check_page(page, y, 20)
            y = _draw_text(page, f"  {i}. {dx}", y, size=9)

    # ── Procedures ──
    procedures = ext.get("procedures", [])
    if procedures:
        page, y = check_page(page, y + 5)
        y = _draw_section_header(page, f"PROCEDURES ({len(procedures)})", y)
        for i, proc in enumerate(procedures, 1):
            page, y = check_page(page, y, 20)
            y = _draw_text(page, f"  {i}. {proc}", y, size=9)

    # ── Vitals ──
    vitals = ext.get("vitals", {})
    vital_items = [(k.replace("_", " ").title(), v) for k, v in vitals.items() if v]
    if vital_items:
        page, y = check_page(page, y + 5)
        y = _draw_section_header(page, "VITALS", y)
        y = _draw_fields(page, vital_items, y)

    # ── Medications ──
    medications = ext.get("medications", [])
    if medications:
        page, y = check_page(page, y + 5, 50)
        y = _draw_section_header(page, f"MEDICATIONS ({len(medications)})", y)
        # Table header
        y = _draw_table_row(page, [("Medication", 35), ("Dose", 250), ("Frequency", 380)], y, header=True)
        for med in medications:
            page, y = check_page(page, y, 20)
            name = med.get("name", "") if isinstance(med, dict) else str(med)
            dose = med.get("dose", "") if isinstance(med, dict) else ""
            freq = med.get("frequency", "") if isinstance(med, dict) else ""
            y = _draw_table_row(page, [(name, 35), (dose, 250), (freq, 380)], y)

    # ── Lab Results ──
    lab_results = ext.get("lab_results", [])
    if lab_results:
        page, y = check_page(page, y + 5, 50)
        y = _draw_section_header(page, f"LAB RESULTS ({len(lab_results)})", y)
        # Table header
        y = _draw_table_row(page, [
            ("Test", 35), ("Result", 200), ("Unit", 310), ("Reference", 420)
        ], y, header=True)
        for lab in lab_results:
            page, y = check_page(page, y, 20)
            name = lab.get("name", "") if isinstance(lab, dict) else str(lab)
            value = lab.get("value", "") if isinstance(lab, dict) else ""
            unit = lab.get("unit", "") if isinstance(lab, dict) else ""
            ref = lab.get("reference_range", "") if isinstance(lab, dict) else ""
            # Color code abnormal results
            color = (0.1, 0.1, 0.1)
            if ref and value:
                try:
                    val_num = float(value)
                    parts = ref.replace(" ", "").split("-")
                    if len(parts) == 2:
                        lo, hi = float(parts[0]), float(parts[1])
                        if val_num < lo or val_num > hi:
                            color = (0.8, 0.15, 0.15)  # Red for abnormal
                except (ValueError, IndexError):
                    pass
            y = _draw_table_row(page, [
                (name, 35), (value, 200), (unit, 310), (ref, 420)
            ], y, color=color)

    # ── Billing Items ──
    billing_items = ext.get("billing_items", [])
    if billing_items:
        page, y = check_page(page, y + 5, 50)
        y = _draw_section_header(page, f"BILLING LINE ITEMS ({len(billing_items)})", y)
        y = _draw_table_row(page, [("Description", 35), ("Code", 350), ("Amount", 460)], y, header=True)
        total = 0
        for item in billing_items:
            page, y = check_page(page, y, 20)
            desc = item.get("description", "") if isinstance(item, dict) else str(item)
            code = item.get("code", "") if isinstance(item, dict) else ""
            amt = item.get("amount", 0) if isinstance(item, dict) else 0
            total += float(amt) if amt else 0
            amt_str = f"INR {float(amt):,.2f}" if amt else "—"
            y = _draw_table_row(page, [(desc, 35), (code or "—", 350), (amt_str, 460)], y)
        # Total row
        page, y = check_page(page, y, 20)
        page.draw_rect(fitz.Rect(30, y, 565, y + 1), color=None, fill=(0.3, 0.3, 0.3))
        y += 3
        y = _draw_table_row(page, [("TOTAL", 350), (f"INR {total:,.2f}", 460)], y, color=(0.22, 0.27, 0.55))

    # ── Reconciliation Alerts ──
    recon_alerts = doc_data.get("reconciliation_alerts", [])
    if recon_alerts:
        page, y = check_page(page, y + 5, 50)
        y = _draw_section_header(page, f"RECONCILIATION ALERTS ({len(recon_alerts)})", y)
        for alert in recon_alerts:
            page, y = check_page(page, y, 35)
            atype = alert.get("alert_type", "").replace("_", " ").title()
            severity = alert.get("severity", "").upper()
            desc = alert.get("description", "")
            color = (0.8, 0.15, 0.15) if severity == "HIGH" else (0.7, 0.5, 0.0)
            y = _draw_text(page, f"[{severity}] {atype}", y, size=9, color=color)
            y = _draw_text(page, desc, y, size=8, color=(0.3, 0.3, 0.3), x=45)
            impact = alert.get("estimated_impact", 0)
            if impact:
                y = _draw_text(page, f"Estimated Impact: INR {impact:,.2f}", y, size=8, color=(0.1, 0.5, 0.1), x=45)
            y += 3

    # ── Confidence Summary ──
    if entities:
        page, y = check_page(page, y + 5, 60)
        y = _draw_section_header(page, "AI CONFIDENCE SUMMARY", y)
        total_ent = len(entities)
        high = sum(1 for e in entities if (e.get("confidence") or 0) >= 0.85)
        med = sum(1 for e in entities if 0.5 <= (e.get("confidence") or 0) < 0.85)
        low = sum(1 for e in entities if (e.get("confidence") or 0) < 0.5 and (e.get("confidence") or 0) > 0)
        review = sum(1 for e in entities if e.get("needs_review"))
        fields = [
            ("Total Entities", str(total_ent)),
            ("High Confidence (>=85%)", str(high)),
            ("Medium Confidence (50-84%)", str(med)),
            ("Low Confidence (<50%)", str(low)),
            ("Pending Review", str(review)),
        ]
        y = _draw_fields(page, fields, y)

    _draw_footer(page, "Generated by Samhita Billing Intelligence", page_num)
    pdf_bytes = doc.tobytes()
    doc.close()
    return pdf_bytes


# ─── FHIR Human-Readable PDF ─────────────────────────────────────────────────

def generate_fhir_pdf(fhir_bundle: dict, doc_data: dict) -> bytes:
    """Generate a human-readable PDF from a FHIR R4 Bundle."""
    if not HAS_FITZ:
        return b""

    doc = fitz.open()
    page = doc.new_page(width=595, height=842)
    page_num = 1

    def check_page(pg, y_pos, needed=40):
        nonlocal page_num
        if y_pos > 800 - needed:
            _draw_footer(pg, "FHIR R4 Bundle — Generated by Samhita Billing Intelligence", page_num)
            pg = doc.new_page(width=595, height=842)
            page_num += 1
            return pg, 50
        return pg, y_pos

    _draw_header(page, "FHIR R4 CLINICAL DOCUMENT", f"HL7 FHIR Standard | {datetime.now().strftime('%d %b %Y %H:%M')}")

    y = 95

    # Parse bundle entries by resource type
    entries = fhir_bundle.get("entry", [])
    resources_by_type = {}
    for entry in entries:
        resource = entry.get("resource", {})
        rtype = resource.get("resourceType", "Unknown")
        resources_by_type.setdefault(rtype, []).append(resource)

    # ── Bundle Info ──
    y = _draw_section_header(page, "BUNDLE INFORMATION", y)
    fields = [
        ("Bundle Type", fhir_bundle.get("type", "collection").title()),
        ("Resource Count", str(len(entries))),
        ("Source Document", doc_data.get("filename", "")),
        ("Bundle ID", fhir_bundle.get("id", "—")),
    ]
    y = _draw_fields(page, fields, y)

    # ── Patient ──
    patients = resources_by_type.get("Patient", [])
    if patients:
        p = patients[0]
        page, y = check_page(page, y + 5)
        y = _draw_section_header(page, "PATIENT", y)
        # Extract name
        names = p.get("name", [{}])
        name_parts = names[0] if names else {}
        full_name = " ".join(name_parts.get("given", [])) + " " + name_parts.get("family", "")
        full_name = full_name.strip() or name_parts.get("text", "Unknown")

        fields = [
            ("Name", full_name),
            ("Gender", (p.get("gender") or "").title()),
            ("Birth Date", p.get("birthDate", "")),
        ]
        # Get identifiers
        for ident in p.get("identifier", []):
            label = ident.get("type", {}).get("text", ident.get("system", "ID"))
            fields.append((label, ident.get("value", "")))
        fields = [(k, v) for k, v in fields if v]
        y = _draw_fields(page, fields, y)

    # ── Conditions / Diagnoses ──
    conditions = resources_by_type.get("Condition", [])
    if conditions:
        page, y = check_page(page, y + 5, 50)
        y = _draw_section_header(page, f"CONDITIONS / DIAGNOSES ({len(conditions)})", y)
        y = _draw_table_row(page, [
            ("Condition", 35), ("Code", 300), ("Status", 450)
        ], y, header=True)
        for cond in conditions:
            page, y = check_page(page, y, 20)
            code_obj = cond.get("code", {})
            text = code_obj.get("text", "")
            codings = code_obj.get("coding", [{}])
            code_str = codings[0].get("code", "") if codings else ""
            system = codings[0].get("system", "") if codings else ""
            # Shorten system URL
            if "icd" in system.lower():
                code_str = f"ICD-10: {code_str}"
            elif "snomed" in system.lower():
                code_str = f"SNOMED: {code_str}"
            status = cond.get("clinicalStatus", {})
            if isinstance(status, dict):
                status_codings = status.get("coding", [{}])
                status = status_codings[0].get("code", "") if status_codings else ""
            y = _draw_table_row(page, [
                (text, 35), (code_str, 300), (str(status).title(), 450)
            ], y)

    # ── Observations (Labs / Vitals) ──
    observations = resources_by_type.get("Observation", [])
    if observations:
        page, y = check_page(page, y + 5, 50)
        y = _draw_section_header(page, f"OBSERVATIONS ({len(observations)})", y)
        y = _draw_table_row(page, [
            ("Observation", 35), ("Value", 280), ("Code", 420)
        ], y, header=True)
        for obs in observations:
            page, y = check_page(page, y, 20)
            code_obj = obs.get("code", {})
            text = code_obj.get("text", "")
            codings = code_obj.get("coding", [{}])
            code_str = codings[0].get("code", "") if codings else ""
            # Value
            vq = obs.get("valueQuantity", {})
            if vq:
                val = f"{vq.get('value', '')} {vq.get('unit', '')}"
            elif obs.get("valueString"):
                val = obs["valueString"]
            else:
                val = "—"
            y = _draw_table_row(page, [(text, 35), (val, 280), (code_str, 420)], y)

    # ── Procedures ──
    procs = resources_by_type.get("Procedure", [])
    if procs:
        page, y = check_page(page, y + 5, 50)
        y = _draw_section_header(page, f"PROCEDURES ({len(procs)})", y)
        for proc in procs:
            page, y = check_page(page, y, 25)
            code_obj = proc.get("code", {})
            text = code_obj.get("text", "")
            codings = code_obj.get("coding", [{}])
            code_str = codings[0].get("code", "") if codings else ""
            status = proc.get("status", "")
            y = _draw_text(page, f"• {text}", y, size=9)
            if code_str:
                y = _draw_text(page, f"  Code: {code_str}  |  Status: {status}", y, size=8, color=(0.4, 0.4, 0.4), x=45)

    # ── MedicationStatements ──
    meds = resources_by_type.get("MedicationStatement", [])
    if meds:
        page, y = check_page(page, y + 5, 50)
        y = _draw_section_header(page, f"MEDICATIONS ({len(meds)})", y)
        for med in meds:
            page, y = check_page(page, y, 25)
            med_code = med.get("medicationCodeableConcept", {})
            text = med_code.get("text", "")
            dosage = med.get("dosage", [{}])
            dose_text = dosage[0].get("text", "") if dosage else ""
            y = _draw_text(page, f"• {text}", y, size=9)
            if dose_text:
                y = _draw_text(page, f"  Dosage: {dose_text}", y, size=8, color=(0.4, 0.4, 0.4), x=45)

    # ── Coverage / Insurance ──
    coverage = resources_by_type.get("Coverage", [])
    if coverage:
        page, y = check_page(page, y + 5)
        y = _draw_section_header(page, "COVERAGE / INSURANCE", y)
        for cov in coverage:
            page, y = check_page(page, y, 30)
            fields = []
            if cov.get("subscriberId"):
                fields.append(("Subscriber ID", cov["subscriberId"]))
            payer = cov.get("payor", [{}])
            if payer and payer[0].get("display"):
                fields.append(("Payer", payer[0]["display"]))
            period = cov.get("period", {})
            if period.get("start"):
                fields.append(("Start", period["start"]))
            if period.get("end"):
                fields.append(("End", period["end"]))
            if fields:
                y = _draw_fields(page, fields, y)

    # ── Claim ──
    claims = resources_by_type.get("Claim", [])
    if claims:
        page, y = check_page(page, y + 5)
        y = _draw_section_header(page, "CLAIM DETAILS", y)
        for claim in claims:
            page, y = check_page(page, y, 30)
            total = claim.get("total", {})
            fields = [
                ("Claim Status", (claim.get("status") or "").title()),
                ("Use", (claim.get("use") or "").title()),
            ]
            if total.get("value"):
                fields.append(("Total Amount", f"INR {float(total['value']):,.2f}"))
            y = _draw_fields(page, fields, y)
            # Claim items
            items = claim.get("item", [])
            if items:
                y = _draw_table_row(page, [("Item", 45), ("Amount", 420)], y, header=True)
                for itm in items:
                    page, y = check_page(page, y, 20)
                    desc = itm.get("productOrService", {}).get("text", f"Item {itm.get('sequence', '')}")
                    net = itm.get("net", {}).get("value", 0)
                    y = _draw_table_row(page, [(desc, 45), (f"INR {float(net):,.2f}" if net else "—", 420)], y)

    # ── All Resource Types Summary ──
    page, y = check_page(page, y + 10, 50)
    y = _draw_section_header(page, "RESOURCE TYPE SUMMARY", y)
    for rtype, resources in sorted(resources_by_type.items()):
        page, y = check_page(page, y, 18)
        y = _draw_text(page, f"  {rtype}: {len(resources)} resource(s)", y, size=9)

    _draw_footer(page, "FHIR R4 Bundle — Generated by Samhita Billing Intelligence", page_num)
    pdf_bytes = doc.tobytes()
    doc.close()
    return pdf_bytes


# ─── Pre-Auth / Billing / Settlement PDFs ─────────────────────────────────────

def generate_pre_auth_pdf(case_data: dict, pre_auth_data: dict, entities: list[dict] = None) -> bytes:
    """Generate a Pre-Authorization form PDF."""
    if not HAS_FITZ:
        return b""

    doc = fitz.open()
    page = doc.new_page(width=595, height=842)

    _draw_header(page, "PRE-AUTHORIZATION REQUEST FORM")

    y = 100
    patient = case_data.get("patient", {})

    y = _draw_section_header(page, "PATIENT INFORMATION", y)
    fields = [
        ("Patient Name", patient.get("name", "")),
        ("Age / Gender", f"{patient.get('age', '')} / {patient.get('gender', '')}"),
        ("Hospital ID", patient.get("patient_id_external", "")),
        ("ABHA ID", patient.get("abha_id", "")),
        ("Case Number", case_data.get("case_number", "")),
    ]
    y = _draw_fields(page, fields, y)

    y = _draw_section_header(page, "INSURANCE DETAILS", y + 10)
    fields = [
        ("TPA / Insurance", case_data.get("tpa_name", "") or case_data.get("insurance_company", "")),
        ("Policy Number", case_data.get("policy_number", "")),
        ("Requested Amount", f"INR {pre_auth_data.get('requested_amount', 0):,.2f}"),
        ("Approval Status", pre_auth_data.get("approval_status", "pending").upper()),
    ]
    if pre_auth_data.get("approved_amount"):
        fields.append(("Approved Amount", f"INR {pre_auth_data['approved_amount']:,.2f}"))
    y = _draw_fields(page, fields, y)

    y = _draw_section_header(page, "CLINICAL DETAILS", y + 10)
    fields = [
        ("Primary Diagnosis", case_data.get("primary_diagnosis", "")),
        ("Primary Procedure", case_data.get("primary_procedure", "")),
        ("Diagnosis Code", case_data.get("primary_diagnosis_code", "")),
        ("Procedure Code", case_data.get("primary_procedure_code", "")),
    ]
    y = _draw_fields(page, fields, y)

    _draw_footer(page, "Generated by Samhita Billing Intelligence")

    pdf_bytes = doc.tobytes()
    doc.close()
    return pdf_bytes


def generate_bill_summary_pdf(case_data: dict, bills: list[dict], pre_auth_data: dict = None) -> bytes:
    """Generate a billing summary PDF."""
    if not HAS_FITZ:
        return b""

    doc = fitz.open()
    page = doc.new_page(width=595, height=842)

    _draw_header(page, "BILLING SUMMARY")

    y = 100
    patient = case_data.get("patient", {})

    y = _draw_section_header(page, "CASE DETAILS", y)
    fields = [
        ("Case Number", case_data.get("case_number", "")),
        ("Patient", patient.get("name", "")),
        ("TPA", case_data.get("tpa_name", "")),
        ("Stage", case_data.get("current_stage", "")),
    ]
    if pre_auth_data:
        fields.append(("Approved Amount", f"INR {pre_auth_data.get('approved_amount', 0):,.2f}"))
    y = _draw_fields(page, fields, y)

    y = _draw_section_header(page, "BILLS", y + 10)
    total = 0
    for bill in bills:
        bill_total = bill.get("total_amount", 0)
        total += bill_total
        y = _draw_text(page, f"  {bill.get('bill_number', '')} ({bill.get('bill_type', '')}) — INR {bill_total:,.2f}  [{bill.get('status', '')}]", y, size=9)
        for item in bill.get("items", [])[:10]:
            y = _draw_text(page, f"    - {item.get('description', '')} x{item.get('quantity', 1)} = INR {item.get('amount', 0):,.2f}", y, size=8, color=(0.3, 0.3, 0.3))
            if y > 780:
                page = doc.new_page(width=595, height=842)
                y = 50

    y = _draw_text(page, f"  TOTAL BILLED: INR {total:,.2f}", y + 5, size=11)

    _draw_footer(page, "Generated by Samhita Billing Intelligence")

    pdf_bytes = doc.tobytes()
    doc.close()
    return pdf_bytes


def generate_settlement_pdf(case_data: dict, settlement_data: dict) -> bytes:
    """Generate a settlement report PDF."""
    if not HAS_FITZ:
        return b""

    doc = fitz.open()
    page = doc.new_page(width=595, height=842)

    _draw_header(page, "SETTLEMENT REPORT")

    y = 100
    patient = case_data.get("patient", {})

    y = _draw_section_header(page, "CASE DETAILS", y)
    fields = [
        ("Case Number", case_data.get("case_number", "")),
        ("Patient", patient.get("name", "")),
        ("TPA", case_data.get("tpa_name", "")),
    ]
    y = _draw_fields(page, fields, y)

    y = _draw_section_header(page, "SETTLEMENT SUMMARY", y + 10)
    fields = [
        ("Billed Amount", f"INR {settlement_data.get('billed_amount', 0):,.2f}"),
        ("Approved Amount", f"INR {settlement_data.get('approved_amount', 0):,.2f}"),
        ("Settled Amount", f"INR {settlement_data.get('settled_amount', 0):,.2f}"),
        ("Total Deductions", f"INR {settlement_data.get('total_deductions', 0):,.2f}"),
        ("Patient Liability", f"INR {settlement_data.get('patient_liability', 0):,.2f}"),
    ]
    y = _draw_fields(page, fields, y)

    deductions = settlement_data.get("deductions", [])
    if deductions:
        y = _draw_section_header(page, "DEDUCTION DETAILS", y + 10)
        for d in deductions:
            y = _draw_text(page, f"  - {d.get('reason', '')} ({d.get('category', '')}) — INR {d.get('amount', 0):,.2f}", y, size=9)

    _draw_footer(page, "Generated by Samhita Billing Intelligence")

    pdf_bytes = doc.tobytes()
    doc.close()
    return pdf_bytes


# ─── Upload to Supabase Storage ──────────────────────────────────────────────

def save_pdf_to_storage(pdf_bytes: bytes, filename: str, case_id: int = None) -> str | None:
    """Save generated PDF to Supabase Storage and return URL."""
    from services.storage import upload_file, BUCKET_GENERATED_PDFS
    path = f"{case_id}/{filename}" if case_id else filename
    return upload_file(path, pdf_bytes, "application/pdf", bucket=BUCKET_GENERATED_PDFS)
